#!/system/bin/sh
insmod /system/lib/modules/overclock.ko omap2_clk_init_cpufreq_table_addr=0xc00505b4
echo 60 > /proc/overclock/max_vsel
echo 800000 > /proc/overclock/max_rate

echo "1 600000" > /proc/overclock/freq_table   
echo "2 400000" > /proc/overclock/freq_table   
echo "3 300000" > /proc/overclock/freq_table 
echo "4 200000" > /proc/overclock/freq_table 


echo "1 200000000 23" > /proc/overclock/mpu_opps 
echo "2 300000000 28" > /proc/overclock/mpu_opps 
echo "3 400000000 35" > /proc/overclock/mpu_opps
echo "4 600000000 48" > /proc/overclock/mpu_opps
